<a href="https://colab.research.google.com/github/heawonjeong/SuanLab/blob/main/_9_%ED%8C%8C%EC%9D%B4%ED%86%A0%EC%B9%98(PyTorch)_%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 파이토치(PyTorch)

<img src="https://img1.daumcdn.net/thumb/R800x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbuUgoV%2FbtqwWZvcHHX%2Fd6XzIFBEfiuFb0UvyV4A50%2Fimg.jpg" width="300">

- 코드 출처: https://pytorch.org/tutorials/

## 파이토치의 구성요소

- `torch`: 텐서를 생성하는 라이브러리

- `torch.autograd`: 자동미분 기능을 제공하는 라이브러리

- `torch.nn`: 신경망을 생성하는 라이브러리

- `torch.multiprocessing`: 병럴처리 기능을 제공하는 라이브러리

- `torch.utils`: 데이터 조작 등 유틸리티 기능 제공

- `torch.legacy`(./nn/.optim): Torch로부터 포팅해온 코드

- `torch.onnx`: ONNX(Open Neural Network Exchange)

  - 서로 다른 프레임워크 간의 모델을 공유할 때 사용

## 텐서(Tensors)
- 넘파이(NumPy)의 ndarray와 유사

- GPU를 사용한 연산 가속도 가능

In [ ]:
import torch
torch.__version__


'2.1.0+cu121'

### 초기화 되지 않은 행렬

In [ ]:
x = torch.empty(4,2)
print(x)

tensor([[1.0752e-05, 1.0300e-11],
        [1.0372e-08, 2.6942e+23],
        [6.7367e-10, 2.5232e-09],
        [1.0524e+21, 1.3109e-08]])


### 무작위로 초기화된 행렬

In [ ]:
x = torch.rand(4,2)
print(x)

tensor([[0.7795, 0.5710],
        [0.7446, 0.9005],
        [0.7610, 0.2239],
        [0.9548, 0.8447]])


### dtype이 long, 0으로 채워진 텐서

In [ ]:
x = torch.zeros(4,2,dtype=torch.long)
print(x)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


In [ ]:
x = torch.tensor([3, 2.3])
print(x)

tensor([3.0000, 2.3000])


In [ ]:
x = x.new_ones(2,4,dtype=torch.double)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


In [ ]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[-1.1866,  1.0850, -0.6319,  1.1331],
        [ 1.7074,  1.8914, -0.2318, -0.7714]])


### 텐서의 크기

In [ ]:
print(x.size())

torch.Size([2, 4])


## 텐서의 연산(operations)

### 덧셈 1

In [ ]:
import math

a = torch.rand(1,2) * 2 -1
print(a)
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))

tensor([[ 0.3247, -0.9121]])
tensor([[0.3247, 0.9121]])
tensor([[1., -0.]])
tensor([[ 0., -1.]])
tensor([[ 0.3247, -0.5000]])


In [ ]:
print(a)
print(torch.min(a))
print(torch.max(a))
print(torch.mean(a))
print(torch.std(a))
print(torch.prod(a))
print(torch.unique(torch.tensor([1,2,3,1,2,2])))

tensor([[ 0.3247, -0.9121]])
tensor(-0.9121)
tensor(0.3247)
tensor(-0.2937)
tensor(0.8746)
tensor(-0.2962)
tensor([1, 2, 3])


### 덧셈2

In [ ]:
x = torch.rand(2,2)
print(x)
print(x.max(dim=0))
print(x.max(dim=1))

tensor([[0.1965, 0.5147],
        [0.3684, 0.2959]])
torch.return_types.max(
values=tensor([0.3684, 0.5147]),
indices=tensor([1, 0]))
torch.return_types.max(
values=tensor([0.5147, 0.3684]),
indices=tensor([1, 0]))


### 덧셈3
- 결과 텐서를 인자로 제공

In [ ]:
print(x)
print(x.min(dim=0))
print(x.min(dim=1))

tensor([[0.1965, 0.5147],
        [0.3684, 0.2959]])
torch.return_types.min(
values=tensor([0.1965, 0.2959]),
indices=tensor([0, 1]))
torch.return_types.min(
values=tensor([0.1965, 0.2959]),
indices=tensor([0, 1]))


### 덧셈4
- `in-place` 방식

- (참고) in-place 방식
  - in-place방식으로 텐서의 값을 변경하는 연산 뒤에는 _''가 붙음
  - `x.copy_(y), x.t_()`

In [ ]:
x = torch.rand(2,2)
print(x)
y = torch.rand(2,2)
print(y)

tensor([[0.3144, 0.9389],
        [0.5405, 0.7313]])
tensor([[0.4902, 0.9347],
        [0.8801, 0.9309]])


In [ ]:
print(torch.add(x, y))
print(x + y)

tensor([[0.8046, 1.8736],
        [1.4206, 1.6622]])
tensor([[0.8046, 1.8736],
        [1.4206, 1.6622]])


In [ ]:
result = torch.empty(2,4)
torch.add(x, y, out=result)
print(result)

tensor([[0.8046, 1.8736],
        [1.4206, 1.6622]])


<ipython-input-27-f1f63580b061>:2: UserWarning: An output with one or more elements was resized since it had shape [2, 4], which does not match the required output shape [2, 2]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at ../aten/src/ATen/native/Resize.cpp:28.)
  torch.add(x, y, out=result)


In [ ]:
print(x)
print(y)
y.add_(x)
print(y)

tensor([[0.3144, 0.9389],
        [0.5405, 0.7313]])
tensor([[0.4902, 0.9347],
        [0.8801, 0.9309]])
tensor([[0.8046, 1.8736],
        [1.4206, 1.6622]])


### 그 외의 연산
- `torch.sub` : 뺄셈

- `torch.mul` : 곱셉

- `torch.div` : 나눗셈

- `torch.mm` : 내적(dot product)

In [ ]:
print(x)
print(y)
print(x - y)
print(torch.sub(x, y))
print(x.sub_(y))

tensor([[0.3144, 0.9389],
        [0.5405, 0.7313]])
tensor([[0.8046, 1.8736],
        [1.4206, 1.6622]])
tensor([[-0.4902, -0.9347],
        [-0.8801, -0.9309]])
tensor([[-0.4902, -0.9347],
        [-0.8801, -0.9309]])
tensor([[-0.4902, -0.9347],
        [-0.8801, -0.9309]])


In [ ]:
print(x)
print(y)
print(x*y)
print(torch.mul(x,y))
print(x.mul(y))

tensor([[-0.4902, -0.9347],
        [-0.8801, -0.9309]])
tensor([[0.8046, 1.8736],
        [1.4206, 1.6622]])
tensor([[-0.3944, -1.7513],
        [-1.2502, -1.5472]])
tensor([[-0.3944, -1.7513],
        [-1.2502, -1.5472]])
tensor([[-0.3944, -1.7513],
        [-1.2502, -1.5472]])


In [ ]:
print(x)
print(y)
print(x/y)
print(torch.div(x,y))
print(x.div(y))

tensor([[-0.4902, -0.9347],
        [-0.8801, -0.9309]])
tensor([[0.8046, 1.8736],
        [1.4206, 1.6622]])
tensor([[-0.6092, -0.4989],
        [-0.6195, -0.5600]])
tensor([[-0.6092, -0.4989],
        [-0.6195, -0.5600]])
tensor([[-0.6092, -0.4989],
        [-0.6195, -0.5600]])


In [ ]:
print(x)
print(y)

print(torch.matmul(x,y))
z=torch.mm(x,y)
print(z)
print(torch.svd(z))

tensor([[-0.4902, -0.9347],
        [-0.8801, -0.9309]])
tensor([[0.8046, 1.8736],
        [1.4206, 1.6622]])
tensor([[-1.7222, -2.4720],
        [-2.0305, -3.1962]])
tensor([[-1.7222, -2.4720],
        [-2.0305, -3.1962]])
torch.return_types.svd(
U=tensor([[-0.6225, -0.7826],
        [-0.7826,  0.6225]]),
S=tensor([4.8379, 0.1003]),
V=tensor([[ 0.5501,  0.8351],
        [ 0.8351, -0.5501]]))


## 텐서의 조작(manipulations)

### 인덱싱
- 넘파이처럼 인덱싱 사용가능

In [ ]:
x = torch.Tensor([[1,2], [3,4]])
print(x)

print(x[0,0])
print(x[0,1])
print(x[1,0])
print(x[1,1])

tensor([[1., 2.],
        [3., 4.]])
tensor(1.)
tensor(2.)
tensor(3.)
tensor(4.)


In [ ]:
print(x[:, 0])
print(x[:,1])

print(x[0, :])
print(x[1, :])

tensor([1., 3.])
tensor([2., 4.])
tensor([1., 2.])
tensor([3., 4.])


### view
- 텐서의 크기(size)나 모양(shape)을 변경

In [ ]:
x = torch.randn(4,5)
print(x)
y = x.view(20)
print(y)
z = x.view(5, -1)
print(z)

tensor([[ 0.0596,  0.1725,  1.1998, -1.0367, -0.1614],
        [-0.3397,  1.2107,  1.4863,  0.1676,  0.7077],
        [-0.8589,  0.2531,  0.7253,  0.7583, -0.3483],
        [ 2.7762,  0.9936,  0.6875, -0.0544,  0.6047]])
tensor([ 0.0596,  0.1725,  1.1998, -1.0367, -0.1614, -0.3397,  1.2107,  1.4863,
         0.1676,  0.7077, -0.8589,  0.2531,  0.7253,  0.7583, -0.3483,  2.7762,
         0.9936,  0.6875, -0.0544,  0.6047])
tensor([[ 0.0596,  0.1725,  1.1998, -1.0367],
        [-0.1614, -0.3397,  1.2107,  1.4863],
        [ 0.1676,  0.7077, -0.8589,  0.2531],
        [ 0.7253,  0.7583, -0.3483,  2.7762],
        [ 0.9936,  0.6875, -0.0544,  0.6047]])


### item
- 텐서에 값이 단 하나라도 존재하면 숫자값을 얻을 수 있음


In [ ]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([-1.3692])
-1.3692399263381958
torch.float32


- 스칼라값 하나만 존재해야함

In [ ]:
x = torch.randn(2) # error
print(x)
print(x.item())
print(x.dtype)

tensor([0.4653, 0.6335])


RuntimeError: a Tensor with 2 elements cannot be converted to Scalar

### squeeze
- 차원을 축소(제거)

In [ ]:
tensor = torch.rand(1,3,3)
print(tensor)
print(tensor.shape)

tensor([[[0.3494, 0.7064, 0.1808],
         [0.4217, 0.9637, 0.5213],
         [0.0309, 0.0483, 0.3474]]])
torch.Size([1, 3, 3])


In [ ]:
t = tensor.squeeze()
print(t)
print(t.shape)

tensor([[0.3494, 0.7064, 0.1808],
        [0.4217, 0.9637, 0.5213],
        [0.0309, 0.0483, 0.3474]])
torch.Size([3, 3])


### unsqueeze
- 차원을 증가(생성)

In [ ]:
t= torch.rand(3,3)
print(t)
print(t.shape)

tensor([[0.0187, 0.4599, 0.4478],
        [0.5188, 0.7407, 0.9074],
        [0.5161, 0.4610, 0.3534]])
torch.Size([3, 3])


In [ ]:
tensor = t.unsqueeze(dim=0)
print(tensor)
print(tensor.shape)

tensor([[[0.0187, 0.4599, 0.4478],
         [0.5188, 0.7407, 0.9074],
         [0.5161, 0.4610, 0.3534]]])
torch.Size([1, 3, 3])


### stack
- 텐서간 결합

In [ ]:
x = torch.FloatTensor([1,4])
print(x)
y = torch.FloatTensor([2, 5])
print(y)
z = torch.FloatTensor([3, 6])
print(z)

print(torch.stack([x,y,z]))


tensor([1., 4.])
tensor([2., 5.])
tensor([3., 6.])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


### cat
- 텐서를 결합하는 메소드(concatenate)

- 넘파이의 `stack`과 유사하지만, 쌓을 dim이 존재해야함
  - 예를 들어, 해당 차원을 늘려준 후 결합


In [ ]:
a = torch.randn(1, 3, 3)
print(a)
b = torch.randn(1,3,3)
print(b)
c = torch.cat((a, b), dim=0)
print(c)
print(c.size())

tensor([[[ 0.1217, -0.1751, -1.2541],
         [ 0.7807, -0.7079, -0.5278],
         [ 0.2867, -1.1764, -1.3500]]])
tensor([[[ 0.8828,  0.5583, -1.9553],
         [-1.6895, -2.1073, -1.0537],
         [ 0.4410,  0.2585, -0.1192]]])
tensor([[[ 0.1217, -0.1751, -1.2541],
         [ 0.7807, -0.7079, -0.5278],
         [ 0.2867, -1.1764, -1.3500]],

        [[ 0.8828,  0.5583, -1.9553],
         [-1.6895, -2.1073, -1.0537],
         [ 0.4410,  0.2585, -0.1192]]])
torch.Size([2, 3, 3])


In [ ]:
c = torch.cat((a, b), dim=1)
print(c)
print(c.size())

tensor([[[ 0.1217, -0.1751, -1.2541],
         [ 0.7807, -0.7079, -0.5278],
         [ 0.2867, -1.1764, -1.3500],
         [ 0.8828,  0.5583, -1.9553],
         [-1.6895, -2.1073, -1.0537],
         [ 0.4410,  0.2585, -0.1192]]])
torch.Size([1, 6, 3])


### chuck
- 텐서를 여러 개로 나눌 때 사용

- 몇 개의 텐서로 나눌 것이냐

In [ ]:
tensor = torch.rand(3,6)
print(tensor)

t1, t2, t3 = torch.chunk(tensor, 3, dim=1)
print(t1)
print(t2)
print(t3)

tensor([[0.0499, 0.8002, 0.1530, 0.9008, 0.6225, 0.9893],
        [0.8708, 0.0057, 0.6372, 0.0804, 0.0891, 0.0592],
        [0.4646, 0.0754, 0.4047, 0.0251, 0.2171, 0.3199]])
tensor([[0.0499, 0.8002],
        [0.8708, 0.0057],
        [0.4646, 0.0754]])
tensor([[0.1530, 0.9008],
        [0.6372, 0.0804],
        [0.4047, 0.0251]])
tensor([[0.6225, 0.9893],
        [0.0891, 0.0592],
        [0.2171, 0.3199]])


### split
- `chunck`와 동일한 기능이지만 조금 다름

- 하나의 텐서당 크기가 얼마이냐

In [ ]:
tensor = torch.rand(3, 6)
t1, t2 = torch.split(tensor, 3, dim=1)
print(tensor)
print(t1)
print(t2)

tensor([[0.1268, 0.0786, 0.9021, 0.6641, 0.9286, 0.2935],
        [0.2705, 0.6543, 0.4544, 0.1072, 0.9369, 0.8713],
        [0.3909, 0.2530, 0.4805, 0.5544, 0.8830, 0.7527]])
tensor([[0.1268, 0.0786, 0.9021],
        [0.2705, 0.6543, 0.4544],
        [0.3909, 0.2530, 0.4805]])
tensor([[0.6641, 0.9286, 0.2935],
        [0.1072, 0.9369, 0.8713],
        [0.5544, 0.8830, 0.7527]])


### torch ↔ numpy
- Torch Tensor(텐서)를 Numpy array(배열)로 변환 가능

  - `numpy()`
  - `from_numpy()`

- (참고)
  - Tensor가 CPU상에 있다면 Numpy 배열은 메모리 공간을 공유하므로 하나가 변하면, 다른 하나도 변함

In [ ]:
a = torch.ones(7)
print(a)

tensor([1., 1., 1., 1., 1., 1., 1.])


In [ ]:
b= a.numpy()
print(b)

[1. 1. 1. 1. 1. 1. 1.]


In [ ]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2. 2. 2.]


In [ ]:
import numpy as np

a = np.ones(7)
b = torch.from_numpy(a)

np.add(a, 1, out=a)
print(a)
print(b) # torch와 numpy에 cpu에 있을 때 메모리를 공유한다

[2. 2. 2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2., 2., 2.], dtype=torch.float64)


## CUDA Tensors
- `.to` 메소드를 사용하여 텐서를 어떠한 장치로도 옮길 수 있음
  - 예) cpu, gpu

In [ ]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([1.1752])
1.1751823425292969
torch.float32


In [ ]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)
y = torch.ones_like(x, device=device)
print(y)
x = x.to(device)
print(x)
z = x+y
print(z)
print(z.to('cpu', torch.double))

cuda
tensor([1.], device='cuda:0')
tensor([1.1752], device='cuda:0')
tensor([2.1752], device='cuda:0')
tensor([2.1752], dtype=torch.float64)


## AUTOGRAD (자동미분)
- autograd 패키지는 Tensor의 모든 연산에 대해 **자동 미분** 제공

- 이는 코드를 어떻게 작성하여 실행하느냐에 따라 역전파가 정의된다는 뜻

- backprop를 위한 미분값을 자동으로 계산

### Tensor

- data: tensor형태의 데이터

- grad: data가 겨쳐온 layer에 대한 미분값 저장

- grad_fn: 미분값을 계산한 함수에 대한 정보 저장 (어떤 함수에 대해서 backprop 했는지)

- `requires_grad` 속성을 `True`로 설정하면, 해당 텐서에서 이루어지는 모든 연산들을 추적하기 시작

- 계산이 완료된 후, `.backward()`를 호출하면 자동으로 `gradient`를 계산할 수 있으며, `.grad` 속성에 누적됨

- 기록을 추적하는 것을 중단하게 하려면, `.detach()`를 호출하여 연산기록으로부터 분리

- 기록을 추적하는 것을 방지하기 위해 코드 블럭을 `with torch.no_grad():`로 감싸면 `gradient`는 필요없지만, `requires_grad=True`로 설정되어 학습 가능한 매개변수를 갖는 모델을 평가(evaluate)할 때 유용

- Autograd 구현에서 매우 중요한 클래스 : `Function` 클래스

- `requires_grad_(...)`는 기존 텐서의 `requires_grad`값을 바꿔치기(`in-place`)하여 변경

### 기울기(Gradient)
- 역전파: `.backward()`를 통해 역전파 계산 가능

- `with torch.no_grad()`를 사용하여 gradient의 업데이트를 하지 않음

- `detach()`: 내용물(content)은 같지만 require_grad가 다른 새로운 Tensor를 가져올 때

### 자동 미분 흐름 다시 보기(1)
- 계산 흐름  
  $a \rightarrow b  \rightarrow c  \rightarrow out $

<br>

## $\quad \frac{\partial out}{\partial a} = ?$
- `backward()`를 통해  
  $a \leftarrow b  \leftarrow c  \leftarrow out $을 계산하면  
    $\frac{\partial out}{\partial a}$값이 `a.grad`에 채워짐


- $b = a + 2$

- $c = b^2$

- a의 `grad_fn`이 None인 이유  
  직접적으로 계산한 부분이 없었기 때문

### 자동 미분 흐름 다시 보기(2)
- `grad`값을 넣어서 `backward`

- 아래의 코드에서 `.grad`값이 None은 gradient값이 필요하지 않기 때문

## nn & nn.functional

- 두 패키지가 같은 기능이지만 방식이 조금 다름

- 위의 `autograd` 관련 작업들을 두 패키지를 통해 진행할 수 있음

- 텐서를 직접 다룰 때 `requires_grad`와 같은 방식으로 진행할 수 있음

- 결론적으로, `torch.nn`은 attribute를 활용해 state를 저장하고 활용하고,  
  `torch.nn.functional`로 구현한 함수의 경우에는 인스턴스화 시킬 필요 없이 사용이 가능



### nn 패키지

- 주로 가중치(weights), 편향(bias)값들이 내부에서 자동으로 생성되는 레이어들을 사용할 때  
  - 따라서, `weight`값들을 직접 선언 안함

- 예시
  - Containers

  - Convolution Layers

  - Pooling layers

  - Padding Layers

  - Non-linear Activations (weighted sum, nonlinearity)

  - Non-linear Activations (other)

  - Normalization Layers

  - Recurrent Layers

  - Transformer Layers

  - Linear Layers

  - Dropout Layers

  - Sparse Layers

  - Distance Functions

  - Loss Functions

  - ..
- https://pytorch.org/docs/stable/nn.html



- Convolution Layer 예시 (1)


### nn.functional 패키지

- 가중치를 직접 선언하여 인자로 넣어줘야함

- 예시)
  - Convolution functions

  - Pooling functions
  
  - Non-linear activation functions

  - Normalization functions

  - Linear functions

  - Dropout functions
  
  - Sparse functions
  
  - Distance functions

  - Loss functions
  - ..

- https://pytorch.org/docs/stable/nn.functional.html

- Convolution Layer 예시 (2)

## Torchvision

- `transforms`: 전처리할 때 사용하는 메소드

- `transforms`에서 제공하는 클래스 이외에  
  일반적으로 클래스를 따로 만들어 전처리 단계를 진행
  
  - 아래의 코드에서 다양한 전처리 기술 확인  
    https://pytorch.org/docs/stable/torchvision/transforms.html


- 예시)
  - `DataLoader`의 인자로 들어갈 `transform`을 미리 정의할 수 있음

  - `Compose`를 통해 리스트 안에 순서대로 전처리 진행

  - 대표적인 예로, `ToTensor`()를 하는 이유는  
   <u>torchvision이 PIL Image형태로만 입력을 받기 때문에</u> 데이터 처리를 위해서 Tensor형으로 변환해야함

## utils.data

- `Dataset`에는 다양한 데이터셋이 존재  
  - MNIST, CIFAR10, ...

- `DataLoader`, `Dataset`을 통해  
  `batch_size`, `train`여부, `transform`등을 인자로 넣어 데이터를 어떻게 load할 것인지 정해줄 수 있음

- `batch_size`만큼 데이터를 하나씩 가져옴

<u>**(중요) torch에서는 channel(채널)이 앞에 옴**</u>

- `channel first`

- tensorflow, keras 등에서는 channel이 뒤에 옴(`channel last`)

### 데이터 확인

## 각 Layer 설명

### nn.Conv2d

- `in_channels`: channel의 갯수

- `out_channels`: 출력 채널의 갯수

- `kernel_size`: 커널(필터) 사이즈

- 텐서플로우, 케라스와 다르게 레이어의 `input`인자에도 값을 집어 넣어줘야함

- `wegiht`확인

- `weight`는 `detach()`를 통해 꺼내줘야 `numpy()`변환이 가능

### Pooling
- `F.max_pool2d`
  - `stride`

  - `kernel_size`

- `torch.nn.MaxPool2d` 도 많이 사용

- MaxPool Layer는 weight가 없기 때문에 바로 `numpy()`변환 가능

### Linear
- 1d만 가능 `.view()`를 통해 1D로 펼쳐줘야함

### Softmax

### F.relu

- ReLU 함수를 적용하는 레이어

- `nn.ReLU`로도 사용 가능

## Optimizer

- `import torch.optim as optim`

- `model`의 파라미터를 업데이트

- 예시)
  ```python
  optimizer = torch.optim.Adam(model.parameters(), lr=1e-4, weight_decay=1e-5)
  optimizer = optim.SGD(model.parameters(), lr=0.001)
  ```

- `.zero_grad()`로 초기화
- `.step()`으로 업데이트

